# Generated by Django 2.2.7 on 2019-11-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwam', '0002_auto_20191113_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='upload',
            field=models.FileField(blank=True, default='default.pdf', upload_to='uploads/'),
        ),
    ]
